version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3.2.1
  jest: blimmer/jest@1.1.1

jobs:
  check-node-version:
    docker:
      - image: cimg/base:2023.12
    steps:
      - checkout
      - run: >
          if [ "$(grep -oP '(?<=nodejs\s).*' .tool-versions)" = "$(cat .node-version)" ]; then
            exit 0
          else
            exit 1
          fi

workflows:
  tests:
    jobs:
      - check-node-version
      - cypress/run:
          cypress-command: npx cypress run --component
          name: e2e tests (cypress)
      - jest/test
