version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    working_directory: ~/transport
    docker:
      - image: cypress/included:3.2.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: which node
      - run: which npm
      - node/install:
          node-version: '14.15.4'
      - run: node --version
      - run: npm --version
      - run: which node
      - run: which npm
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - transport
  tests_e2e:
    working_directory: ~/transport
    docker:
      - image: cypress/included:3.2.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    executor:
      name: node/default
      tag: '14.15.4'
    steps:
      - attach_workspace:
          at: ~/
      - run: node --version
      - run:
          name: Run e2e tests
          command: npm run test:e2e -- --headless
  tests_unit:
    working_directory: ~/transport
    docker:
      - image: cypress/included:3.2.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run jest unit tests
          command: npm run test:unit
workflows:
  workflow:
    jobs:
      - build
      - tests_e2e:
          requires:
            - build
      - tests_unit:
          requires:
            - build
