version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3
  jest: blimmer/jest@1.1.1

jobs:
  check-node-version:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: |
        if [ "$(grep -oP '(?<=nodejs\s).*' .tool-versions)" = "$(cat .node-version)" ]; then 
                  echo "nodejs versions in .tool-versions and .node-version match"
        else 
          echo "nodejs versions in .tool-versions and .node-version are different"
          exit 1
        fi

  workflows:
  tests:
    jobs:
      - check-node-version
      - cypress/run:
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
          name: e2e tests (cypress)
      - jest/test
